-- MODULA TEST: dati demo da creare solo dopo un account TEST.
-- Non eseguire su PROD. Non contiene dati reali.
--
-- Flusso iniziale consigliato:
-- 1. registra un nuovo utente TEST nell'app;
-- 2. nel SQL Editor di MODULA-TEST esegui: select bootstrap_super_admin();
-- 3. crea il tenant demo dall'interfaccia Regia.
--
-- Questa migration è volutamente solo documentativa: gli account Auth e il
-- super-admin devono derivare da un utente TEST reale, non da UUID inventati.
